version: 2

updates:
  - package-ecosystem: "npm"
    directory: /
    target-branch: develop
    schedule:
      interval: "monthly"
    groups:
      all-deps:
        update-types:
          - "major"
          - "minor"
          - "patch"
